name: 'CI: Crispy System'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  artisan-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install-clean &&
          composer install --ignore-platform-reqs

      - run: |
          cp .env.interface .env
          php artisan storage:link
          php artisan key:generate
          ./vendor/bin/sail up -d
          ./vendor/bin/sail artisan test
          ./vendor/bin/sail down
    name: artisan test
